### ISSUE TITLE
Use Circle 2.0 with a custom docker container to reduce boilerplate

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/example-drops-8-composer#103]
Subtask of #61

Making a custom Docker image to test the Terminus Build Tools plugin was actually really easy. See:

- https://github.com/pantheon-systems/docker-php-ci
- https://quay.io/repository/pantheon-public/php-ci
- https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/101

This same technique could be used to reduce the boilerplate currently in the circle.yml in this project. When we convert to Circle 2.0, we can make a custom docker image similar to the one above (except that we will add the Terminus Build Tools plugin & c., and will not add Ruby or the Circle CI tool). Furthermore, we can also put sections of the scripts currently in circle.yml directly into our image.

- Our .circle/config.yml will run scripts at well-known paths in the docker image
- A comment will link to the script in question in the source github repo
- If we update the testig steps in the docker image, all derived projects will get the update
- Folks who want to freeze or customize the test steps can copy them into their .circle dir
- Custom build steps are still done via `composer build-assets`

**Comment by stevector** [comment]
@greg-1-anderson, I imagine in doing this work you'll copy and/or modify the globals set up script @ataylorme put in the WordPress repo. https://github.com/pantheon-systems/example-wordpress-composer/blob/master/.circleci/set-up-globals.sh

That script makes multidevs by pull request number rather than truncated branch name. I just wanted to record that I think that switch is worth making in example-drops-8-composer too and that this work might be a fine place to do it.

**Comment by greg-1-anderson** [comment]
Yes, I think that I will switch to using the pull request number here as well. This means that we won't have a multidev environment until the pull request is created.

The script organization that I have set up here opens up a new possible enhancement that I'm trying to work out right now. It would be possible to have two sets of test scripts: one for testing against a Pantheon site, and another set for running the tests on Circle CI. My idea is to set an environment variable with the path to the scripts we are going to use. We can select the Circle-CI-local scripts if there is no PR yet (has not yet been created), or if there is no Terminus / GitHub token (PR created from an untrusted external repository).

The only thing that's really holding me back from this plan is that folks are likely to write Behat tests that depend on the current state of the database. These tests would fail if the Circle-CI-local scripts ran from a clean install, while the Pantheon tests run from a clone of the dev environment. There are a couple of possible solutions:

- The user could set up an environment variable containing the URL of a sanitized database. If such a thing could be sufficiently sanitized that it would be safe to make it publicly accessible, then we could download an install from that.

- We could organize the Behat tests into two sets: one that assume the site was cloned from dev, and another that do not depend on the site content (so they pass from either a fresh install or from a site cloned from dev).

For some projects, this is not necessary, as all PRs will come from agency members committing directly to the primary GitHub repository. For projects that accept PRs from the community, though, it is very valuable to have these PRs tested as well.

**Comment by stevector** [comment]
> The only thing that's really holding me back from this plan is that folks are likely to write Behat tests that depend on the current state of the database.

Don't let that stop you. There are a few ways to handle that problem. Inside Circle/On Pantheon could also vary with Behat tags, suites, or the filepaths of .feature files so that a test run can complete successfully either way.

I have a D8 personal project that runs Behat tests both inside Circle and on Pantheon on every single build. The Behat tests running inside Circle are meant to pass on a clean DB after site install. The tests running on Pantheon are meant to run against a fully populated DB.

But maybe we're getting ahead of ourselves. Running Behat inside Circle is not on the critical path of switching to Circle 2. I suggest making that a follow up issue. Let's get the benefits of dockerized dependencies first.

**Comment by greg-1-anderson** [comment]
Sounds like a good idea. I'll organize the scripts directory to make this possible, but won't write the on-Circle tests until later.

**Comment by ataylorme** [comment]
> For some projects, this is not necessary, as all PRs will come from agency members committing directly to the primary GitHub repository. For projects that accept PRs from the community, though, it is very valuable to have these PRs tested as well.

I think our focus should be on agency members committing directly to a Git repository, not projects accepting PRs from forks. The primary use of this example, the WordPress example and the build tools plugin have a target audience of agencies using Pantheon. 

These are Pantheon tools developed for our agency users doing client work, not community projects, and I strongly feel the focus of these tools/examples should remain on that use case.

> I have a D8 personal project that runs Behat tests both inside Circle and on Pantheon on every single build. The Behat tests running inside Circle are meant to pass on a clean DB after site install. The tests running on Pantheon are meant to run against a fully populated DB.

This could be done with Circle 2 parallel builds to speed up testing so that Behat tests that don't need real content and can run on a fresh install run at the same time as tests on Pantheon that do require content. Splitting and running the tests concurrently would be faster than running them all in series on Pantheon.

**Comment by greg-1-anderson** [comment]
> This could be done with Circle 2 parallel builds to speed up testing so that Behat tests that don't need real content and can run on a fresh install run at the same time as tests on Pantheon that do require content. Splitting and running the tests concurrently would be faster than running them all in series on Pantheon.

That's a good idea.

**Comment by greg-1-anderson** [comment]
Fixed in #107
