### ISSUE TITLE
Project won't build with a custom upstream

### ISSUE THREAD

**Issue by marklabrecque** [pantheon-systems/example-drops-8-composer#127]
Currently I have a public repo with a custom upstream at https://github.com/marklabrecque/test-upstream and am trying to build a Pantheon CI project leveraging it. It is quite literally an unchanged fork from https://github.com/pantheon-systems/example-drops-8-composer at this point, but it fails on running the following command:

`terminus build:project:create marklabrecque/test-upstream <site-name>

First it asks me for my Github and CircleCI tokens, which appears to work, but then I get the following output:

[notice] Create GitHub project fcv-testing-testing from marklabrecque/test-upstream
 [notice] Call GitHub API: user
 [notice] Creating project and resolving dependencies.
 [notice] Running composer create-project --working-dir=/private/var/folders/c9/4s2vb1x11_s3t5w90mdb0vg1j4l4bd/T/local-siteXLxl8Y marklabrecque/test-upstream fcv-testing-testing -n 

                                                                             
  [InvalidArgumentException]                                                 
  Could not find package marklabrecque/test-upstream with stability stable.  
                                                                             

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

 [error]  Command composer create-project --working-dir=/private/var/folders/c9/4s2vb1x11_s3t5w90mdb0vg1j4l4bd/T/local-siteXLxl8Y marklabrecque/test-upstream fcv-testing-testing -n failed with exit code 1 `

I have verified that the repo is public and that my Github access token is valid.

**Comment by marklabrecque** [comment]
I should also note that running this same command referencing this repo (https://github.com/pantheon-systems/example-drops-8-composer) does work correctly, it's just my fork that does not.

**Comment by stevector** [comment]
Hi @marklabrecque thanks for trying out these CI tools!

The issue you are running into is with that first argument `marklabrecque/test-upstream`. From 
`terminus build:project:create --help`

> Packagist org/name of source template project to fork or path to an existing project on the local filesystem. Paths must either start with ./ or be an absolute path.

So when `pantheon-systems/example-drops-8-composer` as an argument runs successfully, it is not because of https://github.com/pantheon-systems/example-drops-8-composer but rather https://packagist.org/packages/pantheon-systems/example-drops-8-composer. For many Packagist packages, like this one, the github org/name is identical to the Packagist org name, but that is not a hard requirement.

Anyway, your two options are to register your fork on Packagist, more simply, reference a local copy of  https://github.com/marklabrecque/test-upstream. I'd recommend trying the local copy first.

Let me know if that helps!

**Comment by marklabrecque** [comment]
hey @stevector - thanks for the quick response on this one! I knew it was probably something silly like this. Your response makes perfect sense. I won't be able to give this a shot until later tonight probably, but I will be sure to post here and close the issue when I can verify this fix.

Thanks again!

**Comment by greg-1-anderson** [comment]
To make things easier, tag a stable release on your project. You can also run with `--stability=dev` if you don't want to do this, but that might have other unintended consequences (e.g. bringing in non-stable versions of your dependencies)

**Comment by marklabrecque** [comment]
Great suggestions, guys! Thank you. Once I added a local copy of the upstream, it worked like gangbusters.

One question came up during this installation process: it looked like it was installing on Pantheon with upstream "empty". Would the recommended way be to just change the upstream in the pantheon.yml as an extra post-install step or is there a better, more automated way?

Thanks for all of your hard-work on this stuff and the quick turn around on these support items!

**Comment by stevector** [comment]
@marklabrecque no need to change that. Upstreams are the Pantheon-native way of updating core, but part of the purpose of these examples is to use Composer an alternative mechanism for updating core (and all contrib code).

The "empty" upstream is only used because it is hard requirement that every Pantheon site have an upstream designated. That is how Pantheon switches between some minor config difference in nginx and elsewhere to accommodate WordPress vs. D8 vs. D7.
