### ISSUE TITLE
"Icon" exists as a directory in core.

### ISSUE THREAD

**Issue by alphex** [pantheon-systems/example-drops-8-composer#156]
https://github.com/pantheon-systems/example-drops-8-composer/blob/e39ad8e18a04aa2205301e40b86e9fd1fc557108/.gitignore#L91

The "Icon" directory exists in Drupal core.

screen shot : http://z.alphex.io/2018-07-11_14-31-34--d855h.jpg

I'm unsure what the goal of this is, but, maybe just change it to `/Icon` ?

**Comment by alphex** [comment]
Follow up.
I discovered this after having to GIT PULL the project out of Pantheon after building it with composer.

Obviously the composer build doesn't care what's in .gitignore -- but it won't commit it for sure when using the "no build tools" composer deployment process/workflow.

**Comment by alphex** [comment]
`!web/core/lib/Drupal/Core/Layout/Icon`
`!web/core/lib/Drupal/Core/Layout/Icon/`

Maybe something like that?

**Comment by ataylorme** [comment]
I think the negation for the Drupal core directory is the correct approach since we want to continue ignoring the Mac finder `Icon`.

**Comment by nikathone** [comment]
How about something like https://www.drupal.org/project/icon cause I remember having the exact same problem in d7 and I had to `git add -f <path_to_module>`

**Comment by alphex** [comment]
I haven't tested it, @nikathone & @ataylorme 
but does this help https://stackoverflow.com/questions/17556250/how-to-ignore-icon-in-git ???

**Comment by ataylorme** [comment]
That's similar to what we used to put `Icon` in the `.gitignore` in the first place. I think your suggestion of adding a negation for the core directory (`!web/core/lib/Drupal/Core/Layout/Icon`) earlier is the way to go

**Comment by greg-1-anderson** [comment]
I'm -1 on putting invisible files into .gitignore. I think the PR is fine as is; we might also consider loosening up the exclusion (e.g. maybe `!core/**/Icon`) in case more directories of that name are added.

**Comment by kclarkson** [comment]
was there a final solution? I tried @greg-1-anderson suggestion without commenting out the previous icon but nothing worked except deleting the Icon line.

**Comment by alphex** [comment]
Simply removing that line did the trick for me as well.   I guess I should make a REAL pull request :)

**Comment by kikim792** [comment]
We can have neither**Icon** nor **Icon?**
**Icon?** will ignore all directories named **icons**, which are numerous. *Icon* will prevent naming a directory **icon**. Note that files are case insensitive on Macs.

**Comment by greg-1-anderson** [comment]
Yes, I agree. Changing from one icon to a different icon only gave us different problems. We should just remove this.

**Comment by greg-1-anderson** [comment]
Tracking internally as BUGS-2253

**Comment by mcdwayne** [comment]
Just piling on here, as I am messing with Layout builder and hit the Icon issue.  Found this article that says to manually remove it:
https://www.drupal.org/forum/support/upgrading-drupal/2018-04-03/since-drupal-core-upgraded-to-851-from-850

**Comment by grantkruger** [comment]
Like @mcdwayne I've hit this on Layout Builder and I'd also found the issue he pointed to, but in my case icon is not in my .gitignore and it's not a factor anyway because my site is being built on Pantheon using composer via CI, i.e. the problem has nothing to do with git. What happens is I build it locally and the icon folder is there and Layout Builder works fine, but then I push my changes to the Pantheon dev site and CI uses composer on Pantheon to build the site, but this time icon is missing and some Layout Builder functionality now breaks (e.g. trying to add a new section). Seems to be something Pantheon is doing? So now what is the answer? To manually copy the icon folder up? Well, then am I circumventing some PAntheon security decision? Or should I only make Layout Builder changes locally? That could work in my case, though it is not ideal, plus it's not going to work for anyone who wants to give Layout Builder access to more than just devs, and since giving that access to non devs is a big selling point of Layout Builder that is not going to work going forward.

**Comment by jacine** [comment]
I've run into this on most of my Drupal 8 sites, so I would love to see this fixed. It's common to have an "icon" component, which typically looks like:

```
components/icon/
components/icon/icon.twig
components/icon/_icon.scss
```

So, it's not _just_ layout builder that is currently a problem.

**Comment by jacine** [comment]
Awesome! Thank you @greg-1-anderson! 👏
