### ISSUE TITLE
Simple Block "No Further Development"

### ISSUE THREAD

**Issue by generalredneck** [pantheon-systems/example-drops-8-composer#164]
https://github.com/pantheon-systems/example-drops-8-composer/blob/c07b66756a2c7e98fd1d2c0efd2f2ee38273c414/composer.json#L21

checkout https://www.drupal.org/project/simple_block

**Comment by greg-1-anderson** [comment]
Ah, bother. I was using this as an example because the way it stores blocks as config made it much easier to manage static blocks than the Drupal core code, which stores some info in the database and some in config. That makes it more difficult to do the "push config up, pull database down" dev/test/live workflow.

If anyone has a suggestion for a better way to manage blocks (esp wrt block configuration), a PR would be most welcome.

**Comment by generalredneck** [comment]
Totally get it... I don't know the reason "why" they decided to abandon it yet. I personally don't need another project :p just thought I would flag this JIC

**Comment by stevector** [comment]
See https://github.com/pantheon-systems/example-drops-8-composer/pull/221

@greg-1-anderson I think it makes sense for some sites to do Block content as config (rather than content) but I don't think that's a preference we need in this example repo since it goes against what Core does.

**Comment by greg-1-anderson** [comment]
Core is doing it wrong, though. It would be better if we provided a solution rather than just let everyone run into this core limitation. I won't stand in the way of removing the unmaintained module, though.

**Comment by stevector** [comment]
Merged! Thanks for the reviews @greg-1-anderson.
