### ISSUE TITLE
pinning packages question

### ISSUE THREAD

**Issue by alisonjo315** [pantheon-systems/example-drops-8-composer#181]
I'm confused about the two `webflo/*` "pinning" packages.

I read through [#116] (that's where I got the "pinning" term).  Even just in the first response, I was already confused -- I get what `webflo/drupal-core-strict` does, but then the suggestion uses `webflo/drupal-core-require-dev`.

Context: I ended up in this confused place because I hadn't looked at `drupal-composer/drupal-project` in a while, and I saw that they replaced the `require-dev` lines with `webflo/drupal-core-require-dev`.  My own composer-managed Drupal 8 site was originally based on `pantheon-systems/example-drops-8-composer`, so my next step was to look at the composer.json file in this project -- this project requires `webflo/drupal-core-strict` but not `webflo/drupal-core-require-dev` -- so I was just going to ask y'all if you aren't using `drupal-core-require-dev` for a specific reason, or if it simply hasn't happened, no specific reason, and then I came upon issue #116, and now I'm here.

I thiiiiink actually maybe, contrary to how I interpret that issue thread [#116] (and maybe I misunderstood), these two pinning projects don't conflict, they simply do different things, right?  Or?

I had been (sporadically) following the dependencies specified in the `example-drops-8-composer` composer.json, because all our sites are on Pantheon, but now I'm wondering...
1. Do you still recommend using `drupal-core-strict`?  I ask because it's a divergence from `drupal-composer/drupal-project`, so I just want to understand.
1. Are you not using `drupal-core-require-dev` because of a conflict or some other reason, or simply because it hasn't gotten in? (again, I just want to understand)

Thank you!

**Comment by greg-1-anderson** [comment]
We don't use `webflo-drupal-core-require-dev` because it is a subset of `webflow-drupal-core-strict`.

`drupal-composer/drupal-project` does not use `webflow-drupal-core-strict` because it didn't work there for some reason. At least last I was aware, this seemed to be the reason. We use it here because a) it worked, and b) it's good to ensure that the dependencies of your Composer-managed Drupal site are the same as the dependencies tested with the corresponding release of Drupal core.
