### ISSUE TITLE
Update to using PHP Unit 6.5

### ISSUE THREAD

**Issue by albertski** [pantheon-systems/example-drops-8-composer#341]
Ran into errors by using PHP Unit on a Drupal 8.8.1 site.  I believe per reading [here](https://www.drupal.org/project/drupal/issues/2950132), the minimum supported PhpUnit is 6.5. To fix I did the following:

1. Removed `webflo/drupal-core-strict` from composer.json file
2. Updated `"phpunit/phpunit": "^6.5"`

What do you think about that fix?  If you are okay with it I can update this repo and create a pull request.

**Comment by greg-1-anderson** [comment]
webflo/drupal-core-strict has already been removed from HEAD of master. I'll make a PR to update phpunit. It is unfortunately not helpful for folks outside of the GitHub org (pantheon-systems) to make trivial PRs, as I have to push the branch to be owned by someone in the org in order to allow the tests to run (due to CircleCI credentials protection).
