### ISSUE TITLE
Please use a more contemporary php version on composer.json

### ISSUE THREAD

**Issue by chriscalip** [pantheon-systems/example-drops-8-composer#389]
https://github.com/pantheon-systems/example-drops-8-composer/blob/master/composer.json#L115
still uses php 7.0.8 please upgrade to php 7.3

**Comment by greg-1-anderson** [comment]
The version of php recorded in platform.php parallels the minimum php version required by the current stable version of Drupal:

https://git.drupalcode.org/project/drupal/-/blob/8.8.6/core/composer.json#L20

This version will be bumped up once this project is updated to start with Drupal 9 rather than Drupal 8.

Note that this line only controls which dependency versions may be selected by Composer. You may increase this number, or remove the restriction entirely if you wish in your project.  To select what version of PHP is actually being used with your site, please set `php_version` in your pantheon.yml file.

**Comment by chriscalip** [comment]
ok
