### ISSUE TITLE
CircleCI error [RuntimeException] The .git directory is missing

### ISSUE THREAD

**Issue by balcantara90** [pantheon-systems/example-drops-8-composer#421]
We've deployed to CircleCI with an updated composer file and are now getting failed builds.

`[RuntimeException] The .git directory is missing from docroot/modules/contrib/pdf_api.
Script composer install --optimize-autoloader --no-dev handling the build-assets event returned with error code 1`

Looks like the prepareForPantheon functions is stripping  all `.git` folders. Anyone else having similar issues?

**Comment by balcantara90** [comment]
Was able to replicate on my local environment and noticed deleting the `vendor` folder and then doing a `composer install` worked. Resolved in the CircleCI process by removing `- vendor` from the cache paths, then rebuilding the cache.

**Comment by greg-1-anderson** [comment]
PrepareForPantheon strips .git folders by design. If there's a .git directory in vendor (e.g. because you selected a non-stable version of a dependency), then git treats that like a submodule, which is not supported on Panthoen.

The workaround is as you describe: if you need to keep using your project after deploying to Pantheon, remove vendor and run `composer install` again.
