### ISSUE TITLE
Configuration called inside webroot in pantheon.settings.php

### ISSUE THREAD

**Issue by albertski** [pantheon-systems/example-drops-8-composer#69]
The pantheon.settings.php has the configuration set to:

`CONFIG_SYNC_DIRECTORY => 'sites/default/config',`

Can we update it to:

`CONFIG_SYNC_DIRECTORY => '../config',`

**Comment by greg-1-anderson** [comment]
The effective CONFIG_SYNC_DIRECTORY is already set to the location that you mention in [settings.php](https://github.com/pantheon-systems/example-drops-8-composer/blob/master/web/sites/default/settings.php#L23). We set that variable in a different file because we cannot change pantheon.settings.php here.
