### ISSUE TITLE
Gitattribute file not found for 8.3.1

### ISSUE THREAD

**Issue by albertski** [pantheon-systems/example-drops-8-composer#83]
Updating to Drupal 8.3.1 gives the following composer error:

    [Composer\Downloader\TransportException]                                                                                                     
      The "https://raw.githubusercontent.com/pantheon-systems/drops-8/8.3.1/.gitattributes" file could not be downloaded (HTTP/1.1 404 Not Found)

Just hard coded it to 8.3.0 in order for it to work but it would be nice to get it fixed.

**Comment by greg-1-anderson** [comment]
Every time a new release comes out, there is a narrow window of time when this will happen.

- drupal/core has a new tag
- Composer sees it and updates
- Drupal scaffold looks for that tag in drops-8
- The error happens until drops-8 is updated to the new Drupal release.

We can fix this by creating a pantheon-systems/drupal-core repository that is a clone of drupal/core, but that does not gain the release tag until it is available in drops-8.

Closing this issue, because this is solved for 8.3.1, and the general fix is tracked elsewhere (internally)
